project:
  type: website
  output-dir: "docs"

website:
  title: "Anassé Yahanan"
  navbar:
    left: 
      - text: "Accueil"
        file: index.qmd
      - text: "Portofolio"
        file: portofolio.qmd
      - text: "Voir mon VC"
        file: cv.qmd
      
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

